"""
Generate category word files using a real English dictionary.
Downloads a word list, then filters into categories using curated seed words.
"""
import json, os, urllib.request

DICT_URL = "https://raw.githubusercontent.com/dwyl/english-words/master/words_alpha.txt"
DICT_FILE = "english_dict.txt"

def download_dict():
    if os.path.exists(DICT_FILE):
        with open(DICT_FILE) as f:
            return set(w.strip().lower() for w in f if w.strip().isalpha() and 3 <= len(w.strip()) <= 14)
    print("Downloading English dictionary...")
    urllib.request.urlretrieve(DICT_URL, DICT_FILE)
    with open(DICT_FILE) as f:
        words = set(w.strip().lower() for w in f if w.strip().isalpha() and 3 <= len(w.strip()) <= 14)
    print(f"Dictionary: {len(words)} words")
    return words

def load_seeds(filename):
    """Load existing category file as seeds if it exists."""
    if not os.path.exists(filename):
        return set()
    with open(filename) as f:
        data = json.load(f)
    if isinstance(data, list):
        if data and isinstance(data[0], str):
            return set(w.lower() for w in data if isinstance(w, str))
    return set()

def save(name, words):
    clean = sorted(set(w.lower() for w in words if w.isalpha() and 3 <= len(w) <= 14))
    with open(name, 'w') as f:
        json.dump(clean, f, indent=2)
    print(f"{name}: {len(clean)} words")

# Category keyword prefixes/roots - words containing these substrings are likely in-category
CATEGORY_FILTERS = {
    "animals": {
        "contains": ["fish","bird","snake","horse","frog","worm","moth","hawk","duck","foul",
            "deer","wolf","bear","bull","cat","dog","hen","cow","pig","bat","ant","bee","fly",
            "owl","fox","rat","eel","cod","ram","ewe","yak","ape","asp","elk","gnu",
            "hog","jay","kit","nag","pup","roc","tit","doe","dam","cub","kit","foal"],
        "starts": ["aqua","avian","canin","equin","felin","bovin","ovin","porcin","lupin",
            "serp","insect","reptil","mammal","amphi","arachn","crustac","mollus"],
        "ends": ["fish","bird","worm","moth","hawk","duck","frog","snake","mouse","hound",
            "back","tail","wing","claw","horn","mane","paw","fur","fin","gill"]
    },
    "science": {
        "contains": ["chem","phys","bio","gene","cell","atom","molec","neuro","electro",
            "magnet","thermo","optic","photo","micro","macro","proto","nucle","plasma",
            "enzyme","amino","peptid","organ","tissu","bacteri","virus","fungi","metabol",
            "synth","react","solut","crystal","isotop","neutro","proto","electr","radiat"],
        "starts": ["bio","chem","phys","geo","neuro","astro","micro","nano","electro",
            "thermo","photo","hydro","aero","cryo","pyro","spectro","chrono","proto"],
        "ends": ["ology","osis","itis","tion","ment","ase","ide","ate","ine","ium",
            "tron","ogen","osis","esis","lyte","mere","some","plasm","scope","meter"]
    },
    "geography": {
        "contains": ["land","mount","river","ocean","island","lake","coast","valley","desert",
            "forest","plain","cliff","beach","city","town","port","cape","gulf","bay",
            "north","south","east","west","tropic","arctic","polar","equat","hemisph"],
        "starts": ["geo","topo","carto","terr","mount","river","ocean","coast","island",
            "penin","contin","volcan","glaci","platea","canyon","marsh","swamp"],
        "ends": ["land","berg","burg","town","city","port","ford","shire","dale","glen",
            "vale","field","wood","hill","shaw","ham","wick","stead"]
    },
    "music": {
        "contains": ["music","song","sing","note","chord","tone","drum","bass","beat","jazz",
            "rock","folk","tune","hymn","band","solo","duet","trio","lyric","vocal",
            "guitar","piano","flute","horn","harp","bell","organ"],
        "starts": ["music","harmon","melod","rhythm","acoust","orches","sympho","concert",
            "compos","arrang","percus","string","brass","woodwind"],
        "ends": ["phone","phony","chord","tone","beat","drum","horn","bell","song","tune"]
    },
    "movies": {
        "contains": ["film","movie","cinem","actor","scene","screen","drama","comed","thrill",
            "horror","direct","script","cast","plot","star","show","stage","theatr"],
        "starts": ["film","cinem","theatr","drama","comed","screen","direct","product",
            "animat","docum","broadc","televis"],
        "ends": ["film","play","show","cast","scene","drama","graph","scope"]
    },
    "history": {
        "contains": ["histor","war","king","queen","empire","colon","revol","battle","medieval",
            "ancient","dynast","throne","castle","knight","sword","shield","royal","noble",
            "feudal","monarc","democ","republic","conquer","invasi"],
        "starts": ["histor","archae","paleon","chrono","mediev","ancien","colon","imper",
            "dynast","monarc","feud","royal","noble"],
        "ends": ["archy","cracy","ism","dom","ship","hood","ward","craft"]
    },
    "nature": {
        "contains": ["tree","leaf","flower","plant","bush","grass","seed","root","bloom",
            "forest","rain","wind","storm","cloud","snow","sun","moon","star","river",
            "ocean","lake","mount","garden","green","wild","wood","fern","moss","vine"],
        "starts": ["flower","plant","tree","leaf","bloom","garden","forest","rain","storm",
            "cloud","snow","wind","sun","moon","wild","wood","green","herb","botan"],
        "ends": ["tree","leaf","wood","weed","bush","vine","moss","fern","bloom","bud",
            "seed","root","bark","stem","petal","thorn","fruit","berry","flower"]
    },
    "fashion": {
        "contains": ["cloth","dress","shirt","skirt","pant","shoe","boot","coat","hat","silk",
            "lace","satin","velvet","cotton","linen","wool","denim","leather","fabric",
            "stitch","button","zipper","collar","sleeve","pocket","buckle","jewel"],
        "starts": ["cloth","dress","fashion","design","tailor","fabric","garment","apparel",
            "textil","embroi","knit","weav","stitch","sew"],
        "ends": ["wear","cloth","shirt","coat","dress","suit","shoe","boot","hat","band",
            "ring","lace","silk","knit"]
    }
}

def matches_category(word, cat_key):
    filters = CATEGORY_FILTERS[cat_key]
    wl = word.lower()
    for sub in filters.get("contains", []):
        if sub in wl:
            return True
    for pre in filters.get("starts", []):
        if wl.startswith(pre):
            return True
    for suf in filters.get("ends", []):
        if wl.endswith(suf):
            return True
    return False

def main():
    dictionary = download_dict()
    
    # For each category: combine curated seeds + dictionary matches
    # All words must exist in the real English dictionary
    
    # Load curated seed words (the base lists from the old generator were good real words)
    # We'll define them here as known-good real words, then supplement from dict
    
    category_seeds = {
        "animals": [
            "aardvark","abalone","adder","albatross","alligator","alpaca","anaconda","anchovy",
            "angelfish","ant","anteater","antelope","ape","aphid","armadillo","baboon","badger",
            "bandicoot","barnacle","barracuda","bass","bat","beagle","bear","beaver","bee",
            "beetle","bird","bison","blackbird","bluebird","boa","boar","bobcat","bongo",
            "bonito","bonobo","bream","bronco","buffalo","bug","bull","bulldog","bullfrog",
            "bunny","bunting","butterfly","buzzard","camel","canary","capybara","caracal",
            "cardinal","caribou","carp","cassowary","cat","catbird","caterpillar","catfish",
            "cattle","centipede","chameleon","cheetah","chickadee","chicken","chimpanzee","chinchilla",
            "chipmunk","cicada","clam","clownfish","cobra","cockatoo","cockroach","cod",
            "collie","condor","coral","corgi","cormorant","cougar","cow","cowbird","coyote",
            "crab","crane","crayfish","cricket","crocodile","crow","cuckoo","curlew","cuttlefish",
            "dachshund","dalmatian","damselfly","dart","deer","dingo","dipper","doberman","dodo",
            "dog","dogfish","dolphin","donkey","dormouse","dove","dragonfly","drake","duck",
            "duckling","dugong","eagle","earthworm","earwig","echidna","eel","egret","eland",
            "elephant","elk","emu","ermine","falcon","fawn","ferret","finch","firefly",
            "flamingo","flea","flounder","flycatcher","foal","fox","frog","gannet","gar",
            "gazelle","gecko","gerbil","gibbon","giraffe","gnat","gnu","goat","goby",
            "goldfish","goose","gopher","gorilla","grasshopper","grebe","greyhound","grizzly",
            "grosbeak","grouse","grouper","grub","guillemot","gull","guppy","haddock","hagfish",
            "halibut","hamster","hare","harrier","hawk","hedgehog","heron","herring","hippopotamus",
            "hog","honeybee","hoopoe","hornbill","hornet","horse","hound","housefly","husky",
            "hyena","ibex","ibis","iguana","impala","inchworm","insect","jackal","jackdaw",
            "jackrabbit","jaguar","jay","jellyfish","junco","kangaroo","katydid","kestrel",
            "killdeer","kingbird","kingfisher","kite","kitten","kiwi","koala","krill","ladybug",
            "lamb","lamprey","langur","lapwing","lark","leech","lemming","lemur","leopard",
            "limpet","linnet","lion","lizard","llama","loach","lobster","locust","loon",
            "loris","louse","lovebird","lungfish","lynx","macaw","mackerel","magpie","mallard",
            "mamba","manatee","mandrill","manta","mantis","marlin","marmoset","marmot","marten",
            "martin","mastiff","mayfly","meerkat","merlin","midge","millipede","mink","minnow",
            "mite","mockingbird","mole","mollusk","mongoose","monitor","monkey","moose","moray",
            "mosquito","moth","mouse","mule","mullet","muskrat","mussel","mustang","narwhal",
            "nautilus","newt","nighthawk","nightingale","nilgai","numbat","nutcracker","nuthatch",
            "ocelot","octopus","okapi","opossum","orangutan","orca","oriole","oryx","osprey",
            "ostrich","otter","owl","ox","oyster","panda","pangolin","panther","parakeet",
            "parrot","partridge","peacock","peafowl","peccary","pelican","penguin","perch",
            "peregrine","petrel","pheasant","pig","pigeon","pika","pike","pilchard","pintail",
            "piranha","plaice","platypus","plover","pointer","polecat","pollock","pony","poodle",
            "porcupine","porpoise","possum","prawn","primate","pronghorn","ptarmigan","puffin",
            "pug","puma","python","quail","quetzal","quokka","rabbit","raccoon","rail","ram",
            "raptor","rat","rattlesnake","raven","ray","reindeer","reptile","rhino","robin",
            "rodent","rooster","rottweiler","sable","sailfish","salamander","salmon","sandpiper",
            "sardine","sawfish","scallop","scorpion","seahorse","seal","serval","shad","shark",
            "shearwater","sheep","shiner","shrew","shrike","shrimp","skate","skink","skua",
            "skunk","skylark","sloth","slug","smelt","snail","snake","snapper","snipe","sole",
            "songbird","sparrow","spider","sponge","spoonbill","springbok","squid","squirrel",
            "stallion","starfish","starling","stingray","stoat","stork","sturgeon","sunbird",
            "sunfish","swallow","swan","swift","swordfish","tamarin","tanager","tapir","tarantula",
            "tarpon","tarsier","teal","termite","tern","terrapin","terrier","thrush","tick",
            "tiger","tilapia","titmouse","toad","tortoise","toucan","trout","tuna","turbot",
            "turkey","turtle","viper","vireo","vole","vulture","wagtail","wallaby","walleye",
            "walrus","warbler","warthog","wasp","waxwing","weasel","weaver","weevil","whale",
            "whippet","wildcat","wildebeest","wolf","wolverine","wombat","woodcock","woodpecker",
            "worm","wren","yak","zebra","zebu",
        ],
        "science": [
            "abstract","acid","activation","aerobic","algebra","algorithm","alkali","allele",
            "allergy","alloy","altitude","amino","ammonia","amoeba","ampere","amplitude",
            "analysis","anatomy","anemia","anesthesia","angle","antenna","antibiotic","antibody",
            "antidote","antigen","antiseptic","aorta","apparatus","appendix","aquifer","arc",
            "archaea","artery","arthritis","asbestos","asteroid","asthma","astronomy","atom",
            "atomic","atrophy","autopsy","axis","axle","axon","bacillus","bacteria","balance",
            "barium","barometer","base","battery","beam","bedrock","benzene","bicep","bile",
            "binary","biology","biopsy","biotechnology","bladder","blood","boiling","bond",
            "bone","botany","brain","bronchitis","buffer","burner","butane","cadmium","caffeine",
            "calcium","calculus","calorie","cambium","cancer","capacitor","capillary","capsule",
            "carbohydrate","carbon","cardiac","cartilage","catalyst","cathode","cavity","cell",
            "cellular","celsius","centrifuge","cerebral","cesium","charge","chemical","chemistry",
            "chloride","chlorine","chlorophyll","cholesterol","chromium","chromosome","circuit",
            "circulatory","clone","cluster","cobalt","cochlea","codon","coefficient","cognition",
            "coil","collagen","collision","colony","combustion","comet","compound","compression",
            "computer","concave","conception","condensation","conduction","conductor","cone",
            "conservation","constant","contagion","contamination","convection","copper","cornea",
            "corona","corpus","corrosion","cortex","cortisol","cosmic","covalent","cranium",
            "crater","crystal","cubic","culture","current","cuticle","cycle","cylinder","cyst",
            "cytology","cytoplasm","data","decay","decibel","decompose","deficiency","degree",
            "dehydrate","dendrite","density","deposit","dermis","diabetes","diagnosis","diaphragm",
            "diffusion","digestion","digital","dilute","dinosaur","dioxide","dipole","disease",
            "disinfect","dissolve","distill","division","dominant","donor","dopamine","dosage",
            "drought","ductile","dynamo","earthquake","eclipse","ecology","ecosystem","elastic",
            "electrode","electron","element","elevation","embryo","emission","enamel","endocrine",
            "endoscope","energy","entropy","enzyme","epidemic","epidermis","equation","equator",
            "equilibrium","erosion","ethanol","ethics","evaporate","evidence","evolution","exhale",
            "exoskeleton","experiment","explosion","exposure","extinct","extract","eyepiece",
            "fahrenheit","fallout","fatigue","feline","femur","ferment","fern","fertile","fetus",
            "fiber","filament","filter","fission","flagellum","flask","flora","fluoride","flux",
            "focal","focus","follicle","force","forensic","formula","fossil","fraction","fracture",
            "frequency","friction","frontal","frostbite","fructose","fuel","fulcrum","function",
            "fungus","furnace","fusion","galaxy","gallium","gamma","gangrene","gas","gauge",
            "gelatin","gene","generator","genetic","genome","genus","geology","geometry","germ",
            "gestation","geyser","gland","global","glucose","gluon","glycerin","gradient","graft",
            "gram","granite","graph","graphite","gravity","greenhouse","growth","habitat","half",
            "halogen","hazard","heart","heat","helix","helium","hemisphere","hemoglobin","hepatic",
            "herbivore","heredity","hertz","hormone","host","humidity","hybrid","hydrate",
            "hydraulic","hydrogen","hygiene","hypothermia","hypothesis","igneous","immune","impact",
            "impulse","incision","index","indicator","induction","inert","infection","infinite",
            "inflation","infrared","inhale","inherit","injection","inoculate","inorganic","insulate",
            "insulin","integer","intensity","intestine","invertebrate","iodine","ion","ionic",
            "iris","iron","irradiate","irrigate","isotope","joule","junction","kelvin","keratin",
            "kidney","kinetic","kingdom","knot","lactic","lactose","lambda","laminar","larva",
            "laser","lateral","latitude","lattice","lava","lead","lens","lesion","lever","ligament",
            "light","limestone","linear","lipid","liquid","lithium","liver","lobe","logarithm",
            "longitude","lubricant","lumbar","luminous","lunar","lung","lymph","lysine","magma",
            "magnesium","magnet","magnetic","magnify","malaria","malleable","mammal","mandible",
            "manganese","mantle","marble","marine","marrow","mass","matter","maximum","measure",
            "medicine","medium","meiosis","melanin","membrane","mercury","metabolism","metal",
            "meteor","methane","microbe","microscope","migrate","mineral","minimum","mitosis",
            "mixture","model","molecule","molten","momentum","monitor","monocle","mortar","motion",
            "motor","mucus","muscle","mutation","myelin","nasal","natural","nebula","nectar",
            "neon","nephron","nerve","nervous","network","neural","neuron","neutral","neutron",
            "newton","niche","nickel","nitrate","nitrogen","noble","node","nomenclature","normal",
            "nuclear","nuclei","nucleus","nutrient","nylon","observe","occipital","ocean","ohm",
            "opaque","optic","optical","orbit","organ","organic","organism","origin","osmosis",
            "ovary","ovum","oxidation","oxide","oxygen","ozone","palate","pancreas","pandemic",
            "parasite","particle","pascal","pasteurize","pathogen","pattern","pedigree","pelvis",
            "pendulum","penicillin","periodic","peripheral","permeable","petroleum","phase","phenol",
            "phosphate","phosphorus","photon","photosynthesis","physics","pigment","pipette","piston",
            "pituitary","placebo","plague","planet","plankton","plasma","platelet","platinum",
            "plutonium","pneumonia","poison","polar","polarity","pollen","pollinate","pollution",
            "polymer","population","pore","positive","potassium","potential","precipitate","predator",
            "pressure","primary","primate","prism","probe","product","propane","property","prostate",
            "protein","proton","protozoa","pulmonary","pulsar","pulse","pupil","quasar","quartz",
            "quantum","quarantine","radar","radiant","radiation","radical","radius","radon",
            "ratio","reaction","reactor","reagent","receptor","recessive","rectum","recycle",
            "reflect","reflex","refract","regulate","relative","renal","repel","replicate",
            "reproduce","reptile","repulse","research","reservoir","residue","resin","resist",
            "resonance","respiration","retina","revolve","ribosome","rigidity","robot","rocket",
            "rotate","runoff","rust","saline","sample","satellite","saturate","scalar","scale",
            "scalpel","scanner","sediment","seismic","selenium","semen","sensor","sepal","septum",
            "sequence","serum","silicon","silver","simulate","sinus","skeleton","sodium","solar",
            "solenoid","solid","soluble","solution","solvent","sonar","sonic","species","specimen",
            "spectrum","sperm","sphere","spinal","spleen","spore","stable","stamen","static",
            "stem","sterile","steroid","stimulus","stomach","strain","strand","strata","stratum",
            "structure","sublimate","substance","sulfur","supernova","surface","surgery","surplus",
            "survival","suspend","suture","swab","symbiosis","symbol","symmetry","symptom",
            "synapse","syndrome","synthesis","syringe","system","telescope","telomere","temperature",
            "temporal","tendon","tension","terminal","terrain","test","testosterone","theorem",
            "therapy","thermal","thorax","threshold","thyroid","tissue","titanium","topography",
            "torque","toxin","trachea","trait","transfer","transform","transfusion","transistor",
            "transmit","transplant","treatment","tremor","triangle","tritium","tropical","tsunami",
            "tuberculosis","tumor","tungsten","turbine","ultrasound","ultraviolet","umbilical",
            "uniform","uranium","urea","urine","uterus","vaccine","vacuum","valve","vapor",
            "variable","vector","vein","velocity","ventricle","vertebra","vessel","vibration",
            "virus","viscosity","vision","vitamin","voltage","volume","vortex","watt","wavelength",
            "weather","weight","xenon","yield","zinc","zirconium","zone","zoology","zygote",
        ],
        "geography": [
            "africa","alaska","alps","amazon","america","andes","antarctica","arctic","argentina",
            "asia","atlantic","australia","austria","bahamas","basin","bay","beach","belgium",
            "bermuda","bluff","bolivia","border","borough","brazil","bridge","brook","butte",
            "cambodia","cameroon","canada","canal","canyon","cape","capital","caribbean","cascade",
            "cavern","channel","chile","china","city","cliff","climate","coast","colombia",
            "colony","continent","coral","country","county","cove","crater","creek","cuba",
            "current","dam","delta","denmark","desert","district","dune","east","ecuador","egypt",
            "elevation","england","equator","erosion","estuary","ethiopia","europe","everest",
            "fault","fiji","finland","fjord","flood","florida","foothill","ford","forest",
            "formation","france","frontier","frost","gale","germany","geyser","glacier","glen",
            "globe","gorge","grassland","greece","greenland","grove","gulf","gully","harbor",
            "hawaii","hemisphere","highland","hill","holland","horizon","humidity","hurricane",
            "iceland","india","indian","indonesia","inlet","ireland","island","isthmus","italy",
            "jamaica","japan","jungle","kenya","knoll","lagoon","lake","landmark","landscape",
            "latitude","lava","levee","longitude","lowland","mainland","malaysia","map","marsh",
            "meadow","meridian","mesa","meteor","metropolis","mexico","midwest","monsoon","moraine",
            "morocco","mountain","mozambique","nation","navigation","nepal","netherlands","nicaragua",
            "nigeria","north","norway","oasis","ocean","outlet","pacific","pakistan","pampa",
            "panama","park","pass","peak","peninsula","peru","piedmont","plain","plateau","polar",
            "poland","pond","population","port","portugal","prairie","province","quarry","rapids",
            "ravine","reef","region","reservoir","ridge","rift","river","road","romania","rural",
            "russia","sahara","sandbar","savanna","scandinavia","scotland","sea","seashore","season",
            "sediment","settlement","shore","sierra","slope","snow","soil","south","spain","spring",
            "state","steppe","stone","strait","stream","suburb","summit","swamp","sweden",
            "switzerland","taiwan","terrain","territory","thailand","tide","topography","tornado",
            "town","trade","trench","tributary","tropic","tsunami","tundra","tunnel","turkey",
            "typhoon","ukraine","urban","uruguay","utah","valley","vegetation","venezuela","village",
            "volcano","wales","waterfall","watershed","wave","weather","west","wetland","wilderness",
            "wind","woodland","yemen","zambia","zimbabwe","zone",
        ],
        "music": [
            "accordion","acoustic","adagio","allegro","alto","amplifier","anthem","aria","arpeggio",
            "arrangement","artist","audition","bagpipe","ballad","band","banjo","bar","baritone",
            "baroque","bass","bassoon","baton","beat","bell","blues","bolero","bongo","bow",
            "brass","bridge","cadence","calypso","canon","cantata","cello","chamber","chant",
            "chart","choir","choral","chord","chorus","clarinet","classical","clef","coda",
            "composer","composition","concert","concerto","conductor","conga","contralto","cornet",
            "counterpoint","country","crescendo","cymbal","dance","decibel","descant","digital",
            "diminuendo","disco","dissonance","distortion","djembe","dominant","downbeat","drone",
            "drum","drummer","drumstick","duet","dulcimer","dynamics","echo","electronic","encore",
            "ensemble","equalizer","etude","euphonium","expression","falsetto","fanfare","feedback",
            "fiddle","fife","fill","finale","fingering","flamenco","flat","flute","folk","forte",
            "frequency","fret","fugue","funk","fusion","gig","glissando","glockenspiel","gospel",
            "gramophone","groove","grunge","guitar","guitarist","half","harmonica","harmony","harp",
            "harpsichord","headphones","heavy","hertz","horn","hymn","improvisation","indie",
            "instrument","interlude","interval","intonation","intro","jam","jazz","jingle","jive",
            "karaoke","kazoo","kettledrum","key","keyboard","lament","largo","lead","legato",
            "libretto","lullaby","lute","lyric","lyricist","maestro","major","mambo","mandolin",
            "march","marimba","measure","medley","melody","mezzo","microphone","midi","minor",
            "minuet","mixer","modal","modulation","monitor","motif","movement","muse","musical",
            "musician","mute","natural","nocturne","notation","note","octave","ode","opera",
            "operetta","opus","orchestra","orchestration","organ","overtone","overture","passage",
            "patron","pause","pedal","percussion","performance","performer","phrase","pianissimo",
            "pianist","piano","piccolo","pickup","pitch","pizzicato","playlist","pluck","polka",
            "polyphonic","pop","prelude","premiere","presto","producer","progression","psalm","punk",
            "quartet","quaver","quintet","ragtime","rally","rap","rattle","rave","recital","record",
            "recorder","recording","reed","reel","refrain","reggae","register","rehearsal","release",
            "remix","repertoire","reprise","requiem","resonance","rest","reverb","rhapsody","rhythm",
            "riff","rock","rockabilly","rondo","rumba","salsa","samba","sample","sampler",
            "saxophone","scale","scat","score","semitone","serenade","session","sharp","sheet",
            "shuffle","single","sitar","ska","slide","solo","soloist","sonata","song","songwriter",
            "sonic","soprano","soul","sound","soundtrack","speaker","spiritual","staccato","staff",
            "stage","standard","steel","stereo","strain","streaming","string","strum","studio",
            "style","suite","sustain","swing","symphony","syncopation","synth","synthesizer","tabla",
            "tablature","tango","tape","techno","tempo","tenor","theme","theremin","timbre",
            "timpani","tone","tonic","track","transpose","treble","tremolo","triad","triangle",
            "trill","trio","triple","trombone","troubadour","trumpet","tuba","tune","tuner",
            "tuning","turntable","ukulele","unison","upbeat","upright","valve","variation","venue",
            "verse","vibrato","viola","violin","violinist","virtuoso","vivace","vocal","vocalist",
            "voice","volume","waltz","whistle","whole","wind","woodwind","xylophone","yodel","zither",
        ],
        "movies": [
            "action","actor","actress","adaptation","adventure","animation","anime","antagonist",
            "applause","audience","audition","award","backdrop","backstage","biopic","blockbuster",
            "blooper","boom","broadcast","budget","cable","cameo","camera","caption","cartoon",
            "cast","casting","celebrity","censorship","channel","character","choreography","cinema",
            "cinematic","cinematography","classic","climax","clip","closeup","comedy","commentary",
            "commercial","composer","conflict","costume","credit","crew","crime","critic","critique",
            "crossover","cult","curtain","debut","dialogue","digital","director","documentary","dolly",
            "download","drama","dramatic","dramatist","dubbing","editor","effect","emmy","ending",
            "ensemble","entertainment","epic","episode","epilogue","exhibit","experimental","fable",
            "fantasy","farce","feature","festival","fiction","film","filmmaker","filmmaking","finale",
            "flashback","footage","format","franchise","gallery","gangster","genre","ghost","golden",
            "gothic","greenscreen","hero","heroine","highlight","historical","hollywood","hologram",
            "horror","host","imax","improvisation","indie","industry","installment","interlude",
            "intermission","interview","intro","landscape","lead","legend","lens","lighting","lineup",
            "location","longshot","makeup","marquee","masterpiece","matinee","media","melodrama",
            "memoir","metaphor","miniseries","monologue","monster","montage","motion","movie",
            "multiplex","musical","mystery","narration","narrative","narrator","network","newsroom",
            "noir","nomination","nominee","nonfiction","offscreen","onscreen","opening","opus",
            "original","oscar","outtake","overture","pageant","panorama","parody","passion",
            "performance","performer","photogenic","photography","pilot","pitch","pixel","play",
            "playwright","plot","podcast","popcorn","portrait","premiere","prequel","preview",
            "primetime","producer","production","profile","program","prologue","promotion","prop",
            "protagonist","publicist","publicity","puppet","quest","quiz","radio","rating","reality",
            "recap","reel","release","remake","rendition","renewal","repertoire","replay","rerun",
            "resolution","retrospective","reveal","review","reviewer","revival","rewrite","role",
            "romance","romantic","runtime","saga","satire","scene","scenery","score","screen",
            "screening","screenplay","screenwriter","script","scriptwriter","season","segment",
            "sequel","serial","series","setting","short","shot","showdown","showtime","silent",
            "sitcom","sketch","slapstick","slot","sneak","soliloquy","solo","sound","soundtrack",
            "special","spectacle","spectacular","speech","spinoff","sponsor","spotlight","stage",
            "standup","star","stardom","starlet","starring","station","storyboard","storyline",
            "storytelling","streaming","studio","stunt","subplot","subtitle","superhero","superstar",
            "surreal","suspense","symbolism","synopsis","talent","teaser","telecast","television",
            "tension","theatrical","theme","thriller","ticket","timeline","title","tour","track",
            "trailer","treatment","trend","trilogy","triumph","troupe","twist","understudy","variety",
            "venue","version","video","viewer","viewership","villain","vintage","viral","virtual",
            "vision","visual","voiceover","volume","webisode","western","widescreen","winner",
            "workshop","writer","zombie","zoom",
        ],
        "history": [
            "abolition","absolutism","admiral","alliance","ambassador","amendment","amnesty","anarchy",
            "ancestor","ancient","annex","apostle","appeasement","apprentice","aqueduct","arbitration",
            "archaeology","archer","archive","aristocracy","aristocrat","armada","armistice","armor",
            "army","arsenal","artifact","artillery","assassin","assassination","assembly","autocracy",
            "autonomy","aviator","axis","banner","barbarian","barracks","barricade","bastion",
            "battalion","battle","battlefield","bayonet","beacon","betrayal","bishop","blacksmith",
            "blade","blockade","bloodshed","border","boycott","bronze","bunker","bureaucracy","burial",
            "cabinet","cadet","calendar","campaign","canal","cannon","capital","capitalism",
            "capitulation","caravan","cardinal","cartographer","castle","catapult","cathedral","cavalry",
            "ceasefire","census","centurion","century","ceremony","chancellor","chapel","chariot",
            "charter","chieftain","chronicle","chronology","church","citadel","citizen","citizenship",
            "civilization","clan","clergy","coalition","codex","colonialism","colonist","colony",
            "combat","commander","commemoration","commerce","commission","communism","compact",
            "comrade","confederacy","confederation","conflict","conquer","conqueror","conquest",
            "conscription","conspiracy","constitution","consul","convention","coronation","corps",
            "corruption","council","courier","court","covenant","craftsman","creation","creed",
            "crisis","crossbow","crown","crusade","crusader","culture","curfew","currency","czar",
            "dawn","debate","decade","decadence","declaration","decline","decree","defeat","defense",
            "delegate","democracy","democrat","denomination","despot","despotism","detente","dictator",
            "dictatorship","diplomat","diplomacy","disarmament","discovery","dispatch","dissent",
            "dissolution","doctrine","document","domain","dominion","dowager","draft","drought",
            "duke","dungeon","dynasty","earl","edict","election","emancipation","embargo","embassy",
            "emperor","empire","enclave","envoy","epoch","equality","era","erosion","espionage",
            "estate","evolution","excavation","execution","exile","exodus","expansion","expedition",
            "exploration","explorer","export","extinction","faction","famine","fascism","fealty",
            "federal","federation","feminism","feudal","feudalism","fief","fleet","folklore",
            "forerunner","forge","fort","fortification","fortress","fossil","foundation","founder",
            "franchise","freedom","frontier","galleon","galley","garrison","general","generation",
            "genocide","gentry","gladiator","globe","glory","governance","government","governor",
            "grant","guild","guillotine","gunpowder","harbor","harem","harvest","haven","hegemony",
            "heir","heirloom","heraldry","heretic","heritage","hierarchy","historian","historic",
            "history","homeland","homestead","honor","hostage","household","humanism","ideology",
            "immigration","impeachment","imperial","imperialism","inauguration","independence",
            "indigenous","infantry","inflation","influence","innovation","inquisition","inscription",
            "insurrection","integration","intelligence","intervention","invasion","invention","iron",
            "isolation","journal","jubilee","judiciary","jurisdiction","justice","kaiser","khan",
            "king","kingdom","kinship","knight","knighthood","labor","landmark","laureate","law",
            "league","legacy","legend","legendary","legislation","legislature","legion","levy",
            "liberal","liberalism","liberation","liberty","lineage","literacy","lord","loyalty",
            "magistrate","majority","mandate","manifesto","manor","manuscript","maritime","market",
            "marshal","martyr","martyrdom","massacre","medieval","memoir","memorial","mercenary",
            "merchant","mercy","messiah","metropolis","migration","militant","militia","millennium",
            "minister","ministry","minority","miracle","mission","missionary","mobilization",
            "monarchy","monastery","monk","monopoly","monument","morale","mosque","movement",
            "munitions","museum","mutiny","mystic","mythology","nationalism","nation","naval",
            "navigator","negotiation","neutrality","noble","nobleman","nomad","nuclear","oath",
            "obelisk","occupation","offensive","officer","oligarchy","oracle","ordinance","orthodox",
            "outpost","overthrow","pact","pagan","palace","papacy","parish","parliament","partisan",
            "partition","patriarch","patriot","patriotism","patronage","pauper","peace","peasant",
            "pension","persecution","petition","pharaoh","philosopher","philosophy","pilgrimage",
            "pioneer","piracy","pirate","plague","plantation","platform","plunder","policy",
            "politics","pope","populism","portrait","posterity","pottery","poverty","power",
            "precedent","predecessor","premier","presidency","president","priest","prince","princess",
            "principality","prison","prisoner","privateer","privilege","proclamation","propaganda",
            "prophet","prosperity","protector","protectorate","protest","protocol","province",
            "provision","purge","pyramid","queen","quest","radical","raid","railroad","rally",
            "rampart","ransom","ratification","ration","realm","rebellion","reconstruction","reform",
            "reformation","refugee","regency","regent","regime","regiment","reign","relic","religion",
            "renaissance","reparation","repeal","republic","resistance","resolution","restoration",
            "retreat","revelation","revenue","revolt","revolution","revolutionary","rhetoric","ritual",
            "rival","rivalry","royalty","ruin","ruler","ruling","rural","sacrament","sacred",
            "sacrifice","saga","sailor","saint","samurai","sanction","sanctuary","scholar","scripture",
            "secession","secular","senate","senator","sentinel","separation","serf","serfdom",
            "settlement","settler","shield","shogun","siege","slavery","socialism","society",
            "soldier","solidarity","sovereign","sovereignty","spartan","spear","spy","squire",
            "stalemate","state","statecraft","statesman","statue","steward","strategy","stronghold",
            "structure","submarine","succession","successor","suffrage","sultan","summit","superpower",
            "supremacy","surrender","sword","syndicate","tariff","temple","territory","testament",
            "theology","throne","totalitarian","tower","trade","tradition","treason","treasury",
            "treaty","trench","tribal","tribe","tribute","triumph","troop","truce","tyranny",
            "tyrant","union","unification","unity","uprising","urban","utopia","vandal","vanguard",
            "vassal","veteran","viceroy","victory","viking","village","viscount","vision","voyage",
            "warden","warfare","warlord","warrior","weapon","welfare","wilderness","worship","zealot",
        ],
        "nature": [
            "acacia","acorn","agave","alder","alfalfa","algae","almond","aloe","amaranth",
            "anemone","anise","apple","apricot","ash","aspen","aster","azalea","bamboo","banana",
            "bark","barley","basil","bay","bean","beech","begonia","bellflower","birch",
            "blackberry","blossom","bluebell","blueberry","bonsai","borage","boxwood","bracken",
            "bramble","branch","briar","broom","buckeye","bud","bulb","bulrush","burdock",
            "bush","buttercup","cactus","camellia","camphor","canopy","carnation","carob","cattail",
            "cedar","chamomile","cherry","chestnut","chicory","chive","chrysanthemum","cinnamon",
            "citrus","clematis","clover","columbine","comfrey","conifer","coral","coriander",
            "cornflower","cottonwood","cowslip","crocus","crop","currant","cyclamen","cypress",
            "daffodil","dahlia","daisy","dandelion","deadnettle","deciduous","dewdrop","dill",
            "dogwood","duckweed","ebony","edelweiss","elder","elm","eucalyptus","evergreen","fern",
            "fig","fir","fireweed","flax","flower","foliage","forsythia","foxglove","freesia",
            "frond","fruit","fuchsia","gardenia","garlic","geranium","gerbera","ginger","ginkgo",
            "gladiolus","gourd","grape","grapevine","grass","grove","guava","gum","hawthorn",
            "hazel","heather","hemlock","hemp","herb","hibiscus","hickory","holly","hollyhock",
            "honeysuckle","hop","hornbeam","horsetail","hosta","hyacinth","hydrangea","hyssop",
            "iris","ivy","jasmine","jonquil","juniper","kale","kelp","kernel","kudzu","kumquat",
            "lantana","larch","laurel","lavender","leaf","leek","lemon","lettuce","lichen","lilac",
            "lily","linden","liverwort","locust","lotus","lupin","magnolia","mahogany","mallow",
            "mandarin","mangrove","mango","maple","marigold","marjoram","meadow","mesquite",
            "milkweed","mint","mistletoe","moss","mulberry","mushroom","mustard","myrtle","narcissus",
            "nasturtium","nettle","nightshade","nutmeg","oak","oat","oleander","olive","onion",
            "orange","orchid","oregano","palm","pansy","papaya","papyrus","parsley","parsnip",
            "peach","pear","pecan","peony","pepper","peppermint","periwinkle","persimmon","petunia",
            "pine","pineapple","pistachio","plantain","plum","plumeria","poinsettia","pomegranate",
            "poplar","poppy","primrose","privet","pumpkin","quince","radish","raspberry","rattan",
            "redwood","reed","rhododendron","rhubarb","rice","rose","rosemary","rowan","rue","rye",
            "saffron","sage","savanna","sedge","sequoia","shamrock","snapdragon","snowdrop","sorrel",
            "soybean","spearmint","sprout","spruce","squash","starfruit","succulent","sugarcane",
            "sumac","sunflower","sycamore","tamarind","tangerine","taro","tarragon","thistle","thyme",
            "tobacco","tomato","tulip","turmeric","turnip","twig","valerian","vanilla","verbena",
            "vine","violet","walnut","watercress","watermelon","wheat","willow","wisteria","yarrow",
            "yew","yucca","zinnia",
            "air","atmosphere","aurora","autumn","avalanche","blizzard","breeze","brook","cascade",
            "cave","cavern","climate","cloud","coast","cold","condensation","continent","crater",
            "creek","crevasse","current","cyclone","dawn","desert","dew","downpour","drizzle",
            "drought","dusk","dust","earthquake","eclipse","eddy","erosion","estuary","evaporation",
            "flood","fog","foothill","forecast","formation","fossil","freeze","frost","gale",
            "geyser","glacier","glade","glen","gorge","grotto","gravel","gulch","gully","gust",
            "habitat","hail","haze","heat","highland","hilltop","horizon","humidity","hurricane",
            "ice","iceberg","icicle","inlet","island","jungle","lagoon","lake","landform",
            "landscape","landslide","lava","lightning","lowland","marsh","mesa","mineral","mist",
            "monsoon","moon","moonlight","mountain","oasis","ocean","orchard","outcrop","overcast",
            "pebble","peninsula","permafrost","plain","plateau","pond","prairie","precipitation",
            "promontory","quarry","rainbow","ravine","reef","ridge","ripple","river","rivulet",
            "sandbar","sandstone","savannah","scrubland","shoreline","sinkhole","sky","sleet","slope",
            "smog","snow","snowfall","snowflake","solstice","spring","squall","stalactite",
            "stalagmite","steppe","stone","storm","strait","stream","summit","sunrise","sunset",
            "sunshine","surf","swamp","tempest","terrain","thaw","thermal","thunder","thunderstorm",
            "tidal","tide","tornado","torrent","trench","tropic","tropics","tsunami","tundra",
            "twilight","typhoon","valley","volcano","waterfall","watershed","wave","weather","wetland",
            "whirlpool","whirlwind","wildfire","wilderness","wind","woodland","zephyr",
        ],
        "fashion": [
            "anorak","apparel","apron","argyle","armband","ascot","attire","babydoll","backpack",
            "bandana","bangle","barrette","bathrobe","batik","bead","beanie","belt","beret",
            "bermuda","bespoke","bikini","blazer","blouse","boa","bodice","bolero","bonnet","boot",
            "bootie","boutique","bow","bowler","bowtie","boxer","bra","bracelet","braid","brand",
            "breeches","bridal","brim","broadcloth","brocade","brogue","brooch","buckle","buckskin",
            "bunting","burlap","bustle","button","caftan","calico","cambric","camisole","camouflage",
            "canvas","cap","cape","capri","cardigan","cashmere","casual","chain","chambray","charm",
            "check","chenille","chiffon","chintz","choker","cinch","cloak","cloche","clog","coat",
            "cocktail","collar","color","column","corduroy","corset","costume","cotton","couture",
            "cowl","cravat","crease","crepe","crest","crewneck","crinoline","crochet","crop","cuff",
            "cufflink","culottes","cummerbund","damask","dapper","dart","denim","derby","design",
            "designer","diamond","dirndl","distressed","dolman","double","drape","drawstring","dress",
            "dressy","drop","duck","duffel","dungaree","dye","earring","elastic","elegance",
            "elegant","embellish","emblem","emboss","embroider","embroidery","emerald","empire",
            "ensemble","epaulette","espadrille","evening","eyelet","fabric","fad","fashion",
            "fashionista","fastener","faux","feather","fedora","felt","fiber","filigree","finery",
            "finish","fit","fitted","flannel","flap","flare","flat","fleece","flip","floral",
            "flounce","flowing","fluffy","fold","formal","foundation","frame","frayed","fringe",
            "frock","front","full","fur","gabardine","gaiter","galosh","garb","garland","garment",
            "garter","gauze","gemstone","georgette","gilet","gingham","girdle","glam","glamour",
            "glass","glaze","glitter","gloss","glove","gold","gore","gossamer","gown","grain",
            "graphic","grosgrain","gusset","halter","handbag","handkerchief","hanger","harness","hat",
            "haute","headband","headdress","headpiece","heel","hem","hemline","hemp","herringbone",
            "high","hipster","hood","hoodie","hoop","hosiery","houndstooth","hue","inlay","inseam",
            "insole","iron","jacket","jacquard","jeans","jersey","jewel","jewelry","jodhpurs",
            "jumpsuit","kaftan","kerchief","khaki","kimono","kilt","knit","knitwear","knot","lace",
            "laminate","lanyard","lapel","latex","laundry","layer","leather","leggings","length",
            "leopard","leotard","liner","linen","lingerie","lining","locket","loom","loop","lounge",
            "loungewear","luxury","lycra","macrame","madras","maillot","mannequin","mantle","material",
            "matte","maxi","medallion","merino","mesh","metallic","midi","military","millinery",
            "mink","mitten","moccasin","modal","moleskin","monochrome","monogram","motif","muff",
            "muffler","mule","muslin","neckband","neckline","necktie","needle","neoprene","net",
            "neutral","nightgown","nightwear","notch","nubuck","nylon","obi","ombre","onepiece",
            "organza","ornament","outfit","outerwear","overlay","oxford","padding","pageant",
            "paisley","pajama","palazzo","palette","panama","panel","pant","parka","pashmina",
            "patch","patchwork","pattern","pearl","peg","pencil","pendant","petticoat","pigment",
            "pile","pillbox","pin","pinafore","pinstripe","piping","plaid","pleat","plush","pocket",
            "pointed","polo","polyester","pompom","poncho","poplin","pouch","preppy","press","print",
            "pullover","pump","purse","quilt","raffia","raincoat","rawhide","rayon","resort",
            "retro","rhinestone","ribbon","rivet","robe","romper","rosette","ruffle","rug","runway",
            "rustic","sable","sack","safari","sandal","sari","sarong","sash","satin","sateen",
            "scarf","seam","seamstress","sequin","serge","shawl","sheath","sheer","shift","shimmer",
            "shirt","shoe","shoehorn","shoelace","shorts","shoulder","shroud","shuttle","silhouette",
            "silk","silver","skirt","slacks","sleeve","slim","sling","slipper","slit","smock",
            "snap","sneaker","snood","sock","sole","sparkle","spandex","spectacle","spool",
            "sportswear","stain","stash","stay","steamer","stencil","stitch","stocking","stole",
            "stone","strap","strapless","streak","stretch","string","stripe","stud","style","suede",
            "suit","sundress","sunhat","suspender","swagger","sweater","swim","swimsuit","swimwear",
            "synthetic","tack","taffeta","tailor","tailored","tankini","tapestry","tassel","tee",
            "textile","thread","tiara","tie","tint","tip","tissue","toggle","tone","topcoat",
            "topper","toque","torso","tote","train","trapeze","trench","trend","trendy","trim",
            "trouser","trunk","tulle","tunic","turban","turtleneck","tuxedo","tweed","twill",
            "twist","umbrella","undergarment","uniform","unisex","utility","vamp","vanity","veil",
            "velour","velvet","velveteen","vest","vintage","vinyl","viscose","visor","vogue","voile",
            "waist","waistband","waistcoat","wallet","wardrobe","warp","wash","watch","wave","weave",
            "webbing","wedge","welt","wick","width","wig","wingtip","wool","woolen","worsted",
            "wrap","wrist","wristband","yarn","yoke","zipper","zone",
        ]
    }
    
    for cat, seeds in category_seeds.items():
        filename = f"{cat}.json"
        # Start with curated seeds that exist in dictionary
        valid_seeds = set()
        for w in seeds:
            wl = w.lower().strip()
            if wl in dictionary and wl.isalpha() and 3 <= len(wl) <= 14:
                valid_seeds.add(wl)
        
        save(filename, valid_seeds)

if __name__ == "__main__":
    main()
