"""Generate a JSON array of 5,000 technology-related words/phrases."""

from pathlib import Path
import json


TARGET = 5000
OUTPUT = Path(__file__).resolve().parent.parent / "technology_words.json"


def build_word_bank() -> list[str]:
    single_terms = [
        "accelerometer",
        "access point",
        "actuator",
        "ad blocker",
        "adaptive bitrate",
        "address bus",
        "adware",
        "aerial",
        "agritech",
        "algorithm",
        "algorithms",
        "analytics",
        "android",
        "angular velocity sensor",
        "antenna",
        "anti-malware",
        "antivirus",
        "api",
        "api gateway",
        "app",
        "application",
        "applications",
        "appstore",
        "arduino",
        "artificial intelligence",
        "assembly",
        "asset tracking",
        "atmospheric sensor",
        "attestation",
        "audio codec",
        "augmented reality",
        "authenticator",
        "automation",
        "autonomous drone",
        "autonomous systems",
        "autonomous vehicle",
        "availability zone",
        "back end",
        "backend",
        "bandwidth",
        "bare metal",
        "benchmark",
        "biometrics",
        "biosensor",
        "bitcoin",
        "blade server",
        "blockchain",
        "bluetooth",
        "bootloader",
        "bot",
        "botnet",
        "broadband",
        "browser",
        "buffer",
        "bus",
        "cache",
        "caching",
        "cad",
        "camera sensor",
        "captcha",
        "cartridge",
        "cellular modem",
        "certificate authority",
        "chatbot",
        "chromebook",
        "circuit",
        "circuitry",
        "cloud",
        "cloud computing",
        "cloud database",
        "cloud function",
        "cloud storage",
        "cluster",
        "codec",
        "coding",
        "cold storage",
        "compiler",
        "computational geometry",
        "compute shader",
        "computer",
        "computer vision",
        "container",
        "containerization",
        "content delivery network",
        "controller",
        "cookie",
        "coprocessor",
        "core router",
        "cyber defense",
        "cyber hygiene",
        "cyber insurance",
        "cyber range",
        "cyber resilience",
        "cyber risk",
        "cyber range",
        "cybersecurity",
        "data",
        "database",
        "database sharding",
        "datacenter",
        "dataflow",
        "data lake",
        "data mart",
        "data mesh",
        "data pipeline",
        "data science",
        "data warehouse",
        "debugger",
        "deep learning",
        "deepfake",
        "deployment",
        "design system",
        "devops",
        "digital twin",
        "dimm",
        "disassembler",
        "distributed ledger",
        "dns",
        "docker",
        "domain controller",
        "domain name",
        "dsp",
        "edge ai",
        "edge computing",
        "edge gateway",
        "e-health",
        "e-ink",
        "e-learning",
        "e-sim",
        "ethernet",
        "ethernet switch",
        "fabric",
        "failover",
        "fanout",
        "feature store",
        "fiber",
        "firmware",
        "firewall",
        "fleet management",
        "floating point unit",
        "fluxgate",
        "fpga",
        "frontend",
        "full stack",
        "game engine",
        "gateway",
        "geospatial index",
        "gestural interface",
        "git",
        "gpu",
        "graph database",
        "graphql",
        "grid computing",
        "hacking",
        "hardware",
        "hash",
        "hashgraph",
        "hdmi",
        "heatmap",
        "helm chart",
        "heterogeneous compute",
        "heuristics",
        "hologram",
        "host",
        "hotfix",
        "html",
        "hybrid cloud",
        "hyperautomation",
        "hyperconverged",
        "hypergraph",
        "hyperledger",
        "ics",
        "ide",
        "imaging",
        "immersive display",
        "immutable ledger",
        "incident response",
        "industrial IoT",
        "infosec",
        "ingestion",
        "instructions",
        "integrated circuit",
        "intellisense",
        "internet",
        "intranet",
        "inverter",
        "ip camera",
        "ipfs",
        "ipv6",
        "iot",
        "javascript",
        "json",
        "kafka",
        "kubernetes",
        "laser sensor",
        "latency",
        "ledger",
        "lidar",
        "linux",
        "load balancer",
        "logic gate",
        "low-code",
        "machine learning",
        "mainframe",
        "malware",
        "manifold",
        "manufacturing execution system",
        "mesh network",
        "metadata",
        "microchip",
        "microcontroller",
        "microkernel",
        "microlens",
        "microsatellite",
        "microservice",
        "middleware",
        "mobile app",
        "modem",
        "module",
        "monorepo",
        "motherboard",
        "mqtt",
        "nanorobot",
        "nanotechnology",
        "namespace",
        "native app",
        "neural network",
        "neurocomputing",
        "nft marketplace",
        "node",
        "node graph",
        "no-code",
        "object storage",
        "oculus",
        "offchain",
        "oled",
        "operating system",
        "optical drive",
        "optical network",
        "orchestration",
        "packet",
        "packet sniffer",
        "parallelism",
        "passthrough",
        "patch",
        "penetration testing",
        "peripheral",
        "photodiode",
        "pilot line",
        "pipeline",
        "platform",
        "platform engineering",
        "plugin",
        "poc",
        "pod",
        "pointer",
        "post-quantum cryptography",
        "power supply",
        "predictive maintenance",
        "processor",
        "protocol",
        "proxy",
        "python",
        "quantum annealer",
        "quantum computer",
        "quantum cryptography",
        "quantum sensing",
        "query",
        "rack",
        "radar",
        "radio",
        "ransomware",
        "react",
        "real-time analytics",
        "reconfigurable computing",
        "refactoring",
        "regtech",
        "relay",
        "remote sensing",
        "renderer",
        "repl",
        "resistor",
        "responsive design",
        "robot",
        "robotics",
        "router",
        "runtime",
        "satellite",
        "scada",
        "scanner",
        "schema",
        "scripting",
        "sdk",
        "semiconductor",
        "sensor",
        "sensor fusion",
        "server",
        "serverless",
        "service mesh",
        "shell",
        "sim card",
        "simulator",
        "smart contract",
        "smart grid",
        "smart home",
        "smart sensor",
        "sms gateway",
        "sniffer",
        "software",
        "solar inverter",
        "solid state drive",
        "sonar",
        "source control",
        "spark",
        "spoofing",
        "sql",
        "stack",
        "start-up",
        "storage",
        "streaming",
        "supercomputer",
        "support vector machine",
        "surveillance",
        "switch",
        "synchronizer",
        "system",
        "system-on-chip",
        "tableau",
        "tactile sensor",
        "telehealth",
        "telemetry",
        "telepresence",
        "tensor",
        "terminal",
        "terraform",
        "testbench",
        "thermal camera",
        "threat intelligence",
        "tokenization",
        "touchscreen",
        "tracking",
        "transceiver",
        "transformer",
        "turbofan sensor",
        "turbulence model",
        "twin",
        "ultra-wideband",
        "unmanned system",
        "upconverter",
        "uptime",
        "usb",
        "user experience",
        "uv sensor",
        "vector database",
        "version control",
        "virtual machine",
        "virtual reality",
        "voice assistant",
        "volumetric display",
        "vr headset",
        "vulnerability scanner",
        "wan",
        "wearable",
        "web app",
        "web assembly",
        "web server",
        "websocket",
        "wi-fi",
        "widget",
        "windowing system",
        "wireframe",
        "wireless",
        "workflow engine",
        "xcode",
        "yaml",
        "zero knowledge proof",
        "zero trust",
        "zigbee",
        "zoombombing",
    ]

    modifiers = [
        "adaptive",
        "agile",
        "algorithmic",
        "analytical",
        "anomaly-aware",
        "api-first",
        "application-aware",
        "armored",
        "asynchronous",
        "atomic",
        "augmented",
        "autonomous",
        "availability-focused",
        "bandwidth-aware",
        "batch",
        "behavioral",
        "bio-inspired",
        "block-level",
        "boundaryless",
        "cascading",
        "cellular",
        "centralized",
        "circuit-level",
        "cloud",
        "cloud-native",
        "clustered",
        "cognitive",
        "cohesive",
        "collaborative",
        "composable",
        "computation-heavy",
        "concurrent",
        "confidential",
        "connected",
        "container-aware",
        "contextual",
        "continuous",
        "converged",
        "cross-platform",
        "crypto-secure",
        "customer-grade",
        "cyber-physical",
        "data-centric",
        "data-driven",
        "data-first",
        "deep",
        "deterministic",
        "developer-friendly",
        "digital",
        "distributed",
        "edge",
        "elastic",
        "embedded",
        "energy-aware",
        "enterprise",
        "event-driven",
        "fault-tolerant",
        "federated",
        "fine-grained",
        "fleet",
        "flow-based",
        "fog",
        "full-stack",
        "future-proof",
        "geospatial",
        "granular",
        "hardware-accelerated",
        "high-availability",
        "high-bandwidth",
        "high-definition",
        "high-frequency",
        "high-performance",
        "high-throughput",
        "hybrid",
        "immersive",
        "indoor",
        "industrial",
        "intelligent",
        "intent-based",
        "interoperable",
        "intersatellite",
        "intrusion-aware",
        "knowledge-aware",
        "latency-optimized",
        "low-code",
        "low-latency",
        "low-power",
        "low-touch",
        "malware-resistant",
        "mesh",
        "micro",
        "mobile",
        "modular",
        "multi-asset",
        "multi-cloud",
        "multi-core",
        "multi-tenant",
        "neural",
        "next-generation",
        "observable",
        "off-chain",
        "on-chain",
        "on-device",
        "open-source",
        "optimal",
        "parallel",
        "pattern-based",
        "persistent",
        "photonics-enabled",
        "pixel-perfect",
        "policy-aware",
        "predictive",
        "privacy-preserving",
        "programmable",
        "quantum",
        "real-time",
        "resilient",
        "responsive",
        "robotic",
        "satellite",
        "scalable",
        "self-healing",
        "self-learning",
        "self-optimizing",
        "sensor-rich",
        "serverless",
        "signal-ready",
        "smart",
        "software-defined",
        "spatial",
        "stable",
        "stateless",
        "sustainable",
        "trusted",
        "ultra-fast",
        "unified",
        "virtual",
        "vision-based",
        "voice-first",
        "wireless",
        "zero-trust",
    ]

    noun_phrases = [
        "access management",
        "acid analytics",
        "action recognition",
        "actor model",
        "address translation",
        "adversarial modeling",
        "agile architecture",
        "ai governance",
        "ai lifecycle",
        "ai operations",
        "ai safety",
        "air interface",
        "alerting workflow",
        "algorithm pipeline",
        "analytics fabric",
        "anomaly detection",
        "api catalog",
        "api lifecycle",
        "api management",
        "api orchestration",
        "app delivery",
        "app observability",
        "application firewall",
        "application gateway",
        "application mesh",
        "application modernization",
        "asset cloud",
        "asset intelligence",
        "asset lifecycle",
        "asset platform",
        "assistive robotics",
        "astrionics stack",
        "attack graph",
        "attack surface",
        "auditing layer",
        "authentication fabric",
        "automation studio",
        "autonomous operations",
        "availability fabric",
        "backhaul",
        "backup pipeline",
        "behavior analytics",
        "bioinformatics suite",
        "biosurveillance grid",
        "block storage",
        "blockchain bridge",
        "bot defense",
        "business intelligence",
        "cache hierarchy",
        "call control",
        "capacity planning",
        "carrier network",
        "center of excellence",
        "certificate service",
        "chargeback system",
        "cloud access",
        "cloud analytics",
        "cloud backup",
        "cloud brokerage",
        "cloud fabric",
        "cloud firewall",
        "cloud governance",
        "cloud monitoring",
        "cloud native platform",
        "cloud networking",
        "cloud orchestration",
        "cloud readiness",
        "cloud security",
        "cloud telephony",
        "cluster autoscaling",
        "code pipeline",
        "collaboration hub",
        "communication stack",
        "compliance engine",
        "compliance fabric",
        "compute fabric",
        "compute platform",
        "computer graphics",
        "computer vision",
        "configuration drift",
        "configuration plane",
        "connectivity fabric",
        "container orchestration",
        "content protection",
        "control plane",
        "conversational ai",
        "core banking",
        "cost modeling",
        "credential vault",
        "crowd intelligence",
        "crypto custody",
        "customer analytics",
        "customer data platform",
        "cyber analytics",
        "cyber insurance",
        "cyber range",
        "cyber security",
        "dashboard experience",
        "data access",
        "data activation",
        "data anonymization",
        "data api",
        "data broker",
        "data catalog",
        "data classification",
        "data contract",
        "data fabric",
        "data federation",
        "data governance",
        "data graph",
        "data ingestion",
        "data intelligence",
        "data lake",
        "data lineage",
        "data mesh",
        "data observability",
        "data orchestration",
        "data pipeline",
        "data platform",
        "data privacy",
        "data science",
        "data security",
        "data serialization",
        "data services",
        "data sharing",
        "data stack",
        "data standardization",
        "data stewardship",
        "data streaming",
        "data synchronization",
        "data vault",
        "decision intelligence",
        "deep learning",
        "deployment pipeline",
        "developer experience",
        "device intelligence",
        "digital banking",
        "digital engineering",
        "digital forensics",
        "digital identity",
        "digital manufacturing",
        "digital payments",
        "digital signage",
        "digital supply chain",
        "digital thread",
        "digital twin",
        "direct-to-satellite link",
        "disaster recovery",
        "distributed analytics",
        "distributed database",
        "distributed edge",
        "distributed ledger",
        "distributed tracing",
        "document ai",
        "domain-driven design",
        "elastic stack",
        "embedded vision",
        "energy management",
        "enterprise integration",
        "event backbone",
        "event mesh",
        "experience orchestration",
        "feature engineering",
        "field robotics",
        "firmware pipeline",
        "fleet intelligence",
        "fraud analytics",
        "game backend",
        "governance engine",
        "hardware security",
        "hazard detection",
        "high performance computing",
        "identity governance",
        "identity intelligence",
        "identity orchestration",
        "identity verification",
        "image pipeline",
        "incident response",
        "industrial analytics",
        "industrial automation",
        "industrial cloud",
        "information retrieval",
        "infrastructure as code",
        "infrastructure observability",
        "ingest pipeline",
        "innovation lab",
        "inside sales platform",
        "integration fabric",
        "intelligent automation",
        "intent-based networking",
        "inventory management",
        "iot analytics",
        "iot platform",
        "key management",
        "knowledge graph",
        "lab automation",
        "latency monitoring",
        "lifecycle marketing",
        "log analytics",
        "low latency transport",
        "manufacturing cloud",
        "media pipeline",
        "mesh network",
        "metadata layer",
        "mobile analytics",
        "mobile observability",
        "mobility platform",
        "model governance",
        "model hosting",
        "model monitoring",
        "model registry",
        "model serving",
        "monitoring fabric",
        "multi-cloud control plane",
        "network automation",
        "network monitoring",
        "network observability",
        "network optimization",
        "network orchestration",
        "network security",
        "neutral host",
        "object detection",
        "observability pipeline",
        "on-device intelligence",
        "operational analytics",
        "operational technology",
        "optical networking",
        "orchestration layer",
        "output management",
        "payment gateway",
        "penetration testing",
        "performance engineering",
        "performance testing",
        "photonics platform",
        "pipeline automation",
        "platform engineering",
        "platform operations",
        "platform security",
        "policy automation",
        "power management",
        "predictive analytics",
        "predictive maintenance",
        "privacy engineering",
        "process automation",
        "product analytics",
        "production monitoring",
        "profile enrichment",
        "quality engineering",
        "quantum sensing",
        "radar processing",
        "real-time analytics",
        "recovery automation",
        "reference architecture",
        "remote operations",
        "rendering pipeline",
        "resilience engineering",
        "resource scheduler",
        "risk analytics",
        "robot fleet",
        "robotic automation",
        "satellite communications",
        "scada system",
        "scoring engine",
        "search relevance",
        "secure access",
        "security analytics",
        "security fabric",
        "security posture",
        "semantic layer",
        "sensor analytics",
        "sensor platform",
        "service catalog",
        "service discovery",
        "service orchestration",
        "signal processing",
        "site reliability",
        "skilling platform",
        "software delivery",
        "software supply chain",
        "source control",
        "speech analytics",
        "spend intelligence",
        "storage analytics",
        "storage orchestration",
        "supply chain control tower",
        "support automation",
        "surface reconstruction",
        "system integration",
        "talent intelligence",
        "telemetry pipeline",
        "threat detection",
        "threat hunting",
        "ticket intelligence",
        "tokenization service",
        "traffic engineering",
        "traffic management",
        "training pipeline",
        "transaction monitoring",
        "transcoding pipeline",
        "underwriting platform",
        "usage analytics",
        "user analytics",
        "user onboarding",
        "vehicle intelligence",
        "video analytics",
        "video pipeline",
        "virtual desktop",
        "virtual production",
        "vision analytics",
        "voice biometrics",
        "voice orchestration",
        "vulnerability management",
        "warehouse automation",
        "workforce analytics",
        "workflow automation",
        "workplace analytics",
        "zero trust architecture",
    ]

    return single_terms + noun_phrases, modifiers, noun_phrases


def main() -> None:
    base_terms, modifiers, noun_phrases = build_word_bank()
    seen: set[str] = set()
    words: list[str] = []

    def add(term: str) -> None:
        normalized = term.strip()
        if not normalized:
            return
        lowered = normalized.lower()
        if lowered not in seen:
            seen.add(lowered)
            words.append(normalized)

    for term in base_terms:
        add(term)
        if len(words) >= TARGET:
            break

    if len(words) < TARGET:
        for modifier in modifiers:
            for noun in noun_phrases:
                if len(words) >= TARGET:
                    break
                add(f"{modifier} {noun}")
            if len(words) >= TARGET:
                break

    if len(words) < TARGET:
        for noun in noun_phrases:
            for suffix in ("platform", "stack", "service", "workflow", "engine"):
                if len(words) >= TARGET:
                    break
                add(f"{noun} {suffix}")
            if len(words) >= TARGET:
                break

    if len(words) < TARGET:
        raise RuntimeError(f"Only produced {len(words)} words")

    with OUTPUT.open("w", encoding="utf-8") as file:
        file.write("[\n")
        for index, word in enumerate(words[:TARGET]):
            file.write(f"  {json.dumps(word)}")
            file.write(",\n" if index < TARGET - 1 else "\n")
        file.write("]\n")


if __name__ == "__main__":
    main()
